image: registry.gitlab.com/legionarius/template/godot-docker:latest

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: puppets_runner
  VERSION: $(git describe --tags)

linux:
  stage: export
  script:
    - scons platform=linux target=release use_llvm=yes
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux
    expire_in: 2 days

windows:
  stage: export
  script:
    - scons platform=windows target=release
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
    expire_in: 2 days

mac:
  stage: export
  when: manual
  script:
    - scons platform=osx target=release
    - mkdir -v -p build/mac
    - godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac
    expire_in: 2 days
    
html5:
  stage: export
  script:
    - scons platform=javascript target=release
    - mkdir -v -p build/html5
    - godot -v --export "HTML5" build/html5/index.html
  artifacts:
    name: $EXPORT_NAME-web
    paths:
      - build/html5
    expire_in: 2 days

pages:
  stage: deploy
  when: manual
  script:
    - mkdir public
    - cp build/html5/* public
  artifacts:
    paths:
      - public
    expire_in: 1 week
    
android:
  stage: export
  script:
    - echo -n $KEYSTORE_FILE | base64 -d > /root/release.jks
    - sed -i "/keystore\/release=\"\"/ c\keystore\/release=\"/root/release.jks\"" export_presets.cfg
    - sed -i "/keystore\/release_password=\"\"/ c\keystore\/release_password=\"$KEYSTORE_PASSWORD\"" export_presets.cfg
    - sed -i "/keystore\/release_user=\"\"/ c\keystore\/release_user=\"$KEYSTORE_ALIAS\"" export_presets.cfg
    - scons platform=android target=release android_arch=arm64v8
    - scons platform=android target=release 
    - mkdir -v -p build/android
    - godot -v --export "Android" build/android/$EXPORT_NAME.apk
  artifacts:
    name: $EXPORT_NAME-android
    paths:
      - build/android
    expire_in: 2 days



# Itch.io Deploy
itchio:linux:
  stage: deploy
  only:
    - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux --userversion=$CI_COMMIT_TAG
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  only:
    - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows --userversion=$CI_COMMIT_TAG
  dependencies:
    - windows

itchio:macosx:
  stage: deploy
  only:
    - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
  script:
    - butler push ./build/mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac --userversion=$CI_COMMIT_TAG
  dependencies:
    - mac

itchio:android:
  stage: deploy
  only:
    - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
  script:
    - butler push ./build/android $ITCHIO_USERNAME/$ITCHIO_GAME:android --userversion=$CI_COMMIT_TAG
  dependencies:
    - android
